version: 2.1

defaults: &defaults
  working_directory: ~/circleci-members-dashboard
machine:
  node:
    version: 6.7.0
  services:
    - docker

jobs:
  build:
    <<: *defaults
    docker:
    - image: node:10
    steps:
      - checkout
      - run:
          name: elasticbeanstalk
          command: |
              npm install
              REACT_APP_CHAMPAIGN_URL=https://actions.eko.org npm run build
      - run:
          name: list files
          command: |
              ls -R
      - persist_to_workspace:
          root: ~/circleci-members-dashboard
          paths:
            - build
  build_docker_image:
    <<: *defaults
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-members-dashboard/
      - setup_remote_docker
      - run:
          name: list
          command: ls -R
      - run:
          name: Docker build
          command: docker build --rm=false -t  soutech/members_dashboard:$CIRCLE_SHA1 .
      - run:
          name: Docker Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Deploy
          command: ./deploy.sh $CIRCLE_SHA1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - development
      - build_docker_image:
          requires:
            - build
          filters:
            branches:
              only:
                - development
