version: 2.1

defaults: &defaults
  working_directory: ~/circleci-members-dashboard
machine:
  node:
    version: 6.7.0
  services:
    - docker

jobs:
  build:
    <<: *defaults
    docker:
    - image: node:10
    steps:
      - checkout
      - run:
          name: elasticbeanstalk
          command: |
              npm install
              REACT_APP_CHAMPAIGN_URL=https://actions.eko.org npm run build
  build_docker_image:
    <<: *defaults
    docker:
    - image: node:10
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-members-dashboard
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Docker build
          command: docker build --rm=false -t  soutech/members_dashboard:$CIRCLE_SHA1 .
      - run:
          name: Docker Login
          command: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Deploy
          command: ./deploy.sh $CIRCLE_SHA1
      
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - development
      - build_docker_image:
          requires:
            - build
          filters:
            branches:
              only:
                - development
