version: 2.1

defaults: &defaults
  working_directory: ~/circleci-members-dashboard
machine:
  node:
    version: 6.7.0
  services:
    - docker

jobs:
  build:
    <<: *defaults
    docker:
    - image: node:10
    steps:
      - checkout
      - run:
          name: Install packages & build
          command: |
              npm install
              REACT_APP_CHAMPAIGN_URL=https://actions.eko.org npm run build
      - persist_to_workspace:
          root: ~/circleci-members-dashboard
          paths:
            - build

  build_docker_image:
    <<: *defaults
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-members-dashboard/
      - setup_remote_docker
      - run:
          name: Docker build
          command: sh .circleci/build.sh $CIRCLE_SHA1

  deploy_production:
    <<: *defaults
    docker:
      - image: soutech/ruby:2.6-stretch-node-awscli
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-members-dashboard/
      - run:
          name: Deploy
          command: |
            EB_BUCKET=members-dashboard-deployment
            DOCKERRUN_FILE=$CIRCLE_SHA1-Dockerrun.aws.json

            aws configure set default.region $AWS_REGION

            sed "s/<TAG>/$CIRCLE_SHA1/" < .circleci/Dockerrun.aws.json.template > $DOCKERRUN_FILE
            aws s3 cp $DOCKERRUN_FILE s3://$EB_BUCKET/$DOCKERRUN_FILE
            aws elasticbeanstalk create-application-version --application-name members-dashboard \
            --version-label $CIRCLE_SHA1 --source-bundle S3Bucket=$EB_BUCKET,S3Key=$DOCKERRUN_FILE

            aws elasticbeanstalk update-environment --environment-name members-dashboard-env-production \
            --version-label $CIRCLE_SHA1

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - development
      - build_docker_image:
          requires:
            - build
          filters:
            branches:
              only:
                - development
      - deploy_production:
          requires:
            - build_docker_image
          filters:
            branches:
              only:
                - development

